
export default {
    box: {
        width: 900,
        height: 1410,
    },
    container: {
        width: 900,
        height: 1410,
        // marginLeft: 30,
        // borderColor: '#060606',
        position: 'relative',
        backgroundColor: '#62b5d3'
    },
    conImg: {
        width:900,
        height: 1410,
        position: 'absolute',
        top: 0,
        left: 0,
        // position: 'relative',
    },
    header: {
        height: 120,
        width: 860,
      	// backgroundColor: '#ffffff',
        borderBottomWidth: 0.5,
        color: '#ffffff',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        position: 'absolute',
        top: 0,
        left: 0,
        marginLeft: 20,
    },

    title: {
        width: 860,
        fontSize: 48,
        height: 100,
        lineHeight: 100,
        textAlign: 'center',
        fontWeight: 'bold',
        // borderBottomWidth: 6,
        // borderColor: '#000000',
        color: '#ffffff',
        backgroundColor: '#e95893',
        marginTop: 20,
    },
    select: {
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        width: 420,
        fontSize: 48,
        height: 100,
        lineHeight: 120,
        marginTop: 20,
    },
    bgbox: {
        height: 1270,
        width: 860,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        position: 'absolute',
        top: 120,
        left: 0,
        marginLeft: 20,
        // borderRadius: 30,
    },
    listbox: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingLeft: 20,
        paddingRight: 20,
    },
    iocnbutton: {
        width: 260,
        height: 100,
        marginTop: 20,
    },
    top: {
        width: 260,
        height: 100,
        lineHeight: 100,
        color: '#ffffff',
        fontSize: 36,
        textAlign: 'center',
        backgroundColor: '#60b99d',
        marginTop: 20,
        borderRadius: 20,
    },
    rankList: {
        width: 820,
        height: 840,
        backgroundColor: '#1b1c21',
        position: 'absolute',
        top: 140,
        left: 0,
        marginLeft: 20,
    },

    list: {
        width: 820,
        height: 840,
      	backgroundColor: '#ffffff',
    },

    listItem: {
        // backgroundColor: '#7c8184',
        width: 820,
        height: 200,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        // borderRadius: 20,
    },
    frbox: {
        width: 820,
        height: 200,
        // position: 'absolute',
        // top: 0,
        // left: 0,
    },
    gift: {
        width: 80,
        height: 80,
        position: 'absolute',
        top: 60,
        right: 40,
        backgroundColor: 'red'
    },
    // listItemOld: {
    //    backgroundColor: '#ffffff',
    // },

    listItemNum: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#ffffff',
        lineHeight: 200,
        height: 200,
        textAlign: 'center',
        width: 120,
    },

    listHeadImg: {
        borderRadius: 6,
        width: 90,
        height: 90,
        color: '#000000',
    },

    listItemScore: {
        fontSize: 48,
        fontWeight: 'bold',
        marginLeft : 10,
        height: 200,
        lineHeight: 200,
        width: 260,
        textAlign: 'right',
        color: '#ffffff',
    },

    listItemName:{
        fontSize: 36,
        height: 70,
        lineHeight: 70,
        width: 240,
        marginLeft: 30,
        color: '#ffffff',
    },
    numbertop: {
        fontSize: 36,
        height: 70,
        lineHeight: 70,
        width: 240,
        marginLeft: 30,
        color: '#59d4fe',
    },

    listScoreUnit: {
        opacity: 0.5,
        color: '#000000',
        fontSize: 30,
        height: 200,
        lineHeight: 200,
        marginLeft: 8,
        color: '#ffffff',
    },

    selfListItem: {
        borderRadius: 20,
        marginTop: 50,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        color: '#000000',
    },
  	// listTips: {
    //   	width: 860,
    //     height: 90,
    //   	lineHeight: 90,
    //   	textAlign: 'center',
    //   	fontSize: 30,
    //   	color: 'rgba(0,0,0,0.5)',
    //   	backgroundColor: '#ffffff',
    //     borderRadius: 10,
    //     /*borderWidth: 1,
    //     borderColor: 'rgba(0, 0, 0, 0.3)',*/
    // }
    buttonshare:{
        width: 900,
        height: 120,
        fontSize: 48,
        lineHeight: 120,
        color: 'rgba(0,0,0,0.5)',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 40,
    },
    share: {
        width: 300,
        height: 120,
        textAlign: 'center',
        marginRight: 40,
    },
    ranking: {
        width: 300,
        height: 120,
        fontSize: 42,
        lineHeight: 120,
        textAlign: 'center',
        color: '#ffffff',
    }
}

